"""
build_book.py
=============
Build a polished, self-contained PDF retelling of Chapter 5 of
*AI-Powered Search*. Prose in `content/*.md`, diagrams generated by
`graphics.py`, assembled here into a single 30-40 page book chapter.

Usage:
    python3 build_book.py

Outputs:
    chapter-5-plain-english.pdf      (in this folder)
    graphics/*.png                    (auto-regenerated)
"""

from __future__ import annotations

import datetime as dt
import re
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Image,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

import graphics as gfx_module

# ---------------------------------------------------------------------------
# Palette + styles
# ---------------------------------------------------------------------------

PAL = {
    "navy":         colors.HexColor("#1a1a2e"),
    "teal":         colors.HexColor("#00796B"),
    "teal_soft":    colors.HexColor("#B2DFDB"),
    "teal_bg":      colors.HexColor("#E0F2F1"),
    "coral":        colors.HexColor("#E76F51"),
    "coral_soft":   colors.HexColor("#FAD2C7"),
    "ink":          colors.HexColor("#212121"),
    "muted":        colors.HexColor("#616161"),
    "rule":         colors.HexColor("#BDBDBD"),
    "code_bg":      colors.HexColor("#F5F5F5"),
    "tip_bg":       colors.HexColor("#E3F2FD"),
    "tip_border":   colors.HexColor("#1976D2"),
    "warn_bg":      colors.HexColor("#FFF3E0"),
    "warn_border":  colors.HexColor("#F57C00"),
    "tech_bg":      colors.HexColor("#ECEFF1"),
    "tech_border":  colors.HexColor("#546E7A"),
    "rem_bg":       colors.HexColor("#E8F5E9"),
    "rem_border":   colors.HexColor("#388E3C"),
    "note_bg":      colors.HexColor("#FAFAFA"),
    "note_border":  colors.HexColor("#9E9E9E"),
}

CALLOUT_RULES = [
    (r"\*\*\s*Tip[.:]\s*\*\*\s*",            "TIP",        "tip_bg",  "tip_border"),
    (r"\*\*\s*Warning[.:]\s*\*\*\s*",        "WARNING",    "warn_bg", "warn_border"),
    (r"\*\*\s*Technical Stuff[.:]\s*\*\*\s*","TECHNICAL",  "tech_bg", "tech_border"),
    (r"\*\*\s*Remember[.:]\s*\*\*\s*",       "REMEMBER",   "rem_bg",  "rem_border"),
]

FIGURE_LINE = re.compile(r"^\s*\[FIGURE:\s*([A-Za-z0-9_]+)\s*\]\s*$")


def build_styles() -> dict:
    base = getSampleStyleSheet()
    body_font, bold_font, italic_font = "Helvetica", "Helvetica-Bold", "Helvetica-Oblique"
    code_font = "Courier"

    s = {}
    # Title page
    s["TitleEyebrow"] = ParagraphStyle(
        "TitleEyebrow", parent=base["Normal"],
        fontName=bold_font, fontSize=11, leading=14,
        textColor=PAL["teal"], alignment=TA_CENTER, spaceAfter=10,
    )
    s["TitleMain"] = ParagraphStyle(
        "TitleMain", parent=base["Title"],
        fontName=bold_font, fontSize=38, leading=46,
        textColor=PAL["navy"], alignment=TA_CENTER, spaceAfter=20,
    )
    s["TitleSubtitle"] = ParagraphStyle(
        "TitleSubtitle", parent=base["Normal"],
        fontName=italic_font, fontSize=15, leading=22,
        textColor=PAL["muted"], alignment=TA_CENTER, spaceAfter=8,
    )
    s["TitleFootnote"] = ParagraphStyle(
        "TitleFootnote", parent=base["Normal"],
        fontName=body_font, fontSize=9.5, leading=14,
        textColor=PAL["muted"], alignment=TA_CENTER,
    )

    # Body text
    s["H1"] = ParagraphStyle(
        "H1", parent=base["Heading1"],
        fontName=bold_font, fontSize=24, leading=30,
        textColor=PAL["navy"],
        spaceBefore=14, spaceAfter=14, keepWithNext=True,
    )
    s["H2"] = ParagraphStyle(
        "H2", parent=base["Heading2"],
        fontName=bold_font, fontSize=16, leading=22,
        textColor=PAL["teal"],
        spaceBefore=16, spaceAfter=6, keepWithNext=True,
    )
    s["H3"] = ParagraphStyle(
        "H3", parent=base["Heading3"],
        fontName=bold_font, fontSize=12, leading=16,
        textColor=PAL["navy"],
        spaceBefore=10, spaceAfter=4, keepWithNext=True,
    )
    s["Body"] = ParagraphStyle(
        "Body", parent=base["BodyText"],
        fontName=body_font, fontSize=10.5, leading=15.5,
        textColor=PAL["ink"],
        spaceAfter=9, alignment=TA_JUSTIFY,
    )
    s["ListItem"] = ParagraphStyle(
        "ListItem", parent=s["Body"],
        leftIndent=18, bulletIndent=4, spaceAfter=4,
        alignment=TA_LEFT,
    )
    s["Caption"] = ParagraphStyle(
        "Caption", parent=base["Normal"],
        fontName=italic_font, fontSize=9, leading=12,
        textColor=PAL["muted"], alignment=TA_CENTER,
        spaceBefore=4, spaceAfter=16,
    )
    s["CalloutLabel"] = ParagraphStyle(
        "CalloutLabel", parent=base["Normal"],
        fontName=bold_font, fontSize=9, leading=12,
        textColor=colors.white,
    )
    s["CalloutBody"] = ParagraphStyle(
        "CalloutBody", parent=s["Body"],
        fontSize=10, leading=14, spaceAfter=0,
    )
    s["TableHeader"] = ParagraphStyle(
        "TableHeader", parent=s["Body"],
        fontName=bold_font, fontSize=9.5, leading=12,
        textColor=colors.white, spaceAfter=0,
    )
    s["TableCell"] = ParagraphStyle(
        "TableCell", parent=s["Body"],
        fontSize=9.5, leading=12, spaceAfter=0,
        alignment=TA_LEFT,
    )
    return s


# ---------------------------------------------------------------------------
# Inline markdown formatting
# ---------------------------------------------------------------------------

EMOJI_DROP = re.compile(r"[\U0001F300-\U0001FAFF]|[☀-➿]")


def strip_emoji(text: str) -> str:
    return EMOJI_DROP.sub("", text)


def inline_format(text: str) -> str:
    text = strip_emoji(text)
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    # inline code first
    text = re.sub(
        r"`([^`]+)`",
        r'<font face="Courier" size="9.5" backColor="#F5F5F5">\1</font>',
        text,
    )
    # links: [text](url) -> text
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"\1", text)
    # bold
    text = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", text)
    # italic
    text = re.sub(r"(?<!\w)\*([^*\n]+?)\*(?!\w)", r"<i>\1</i>", text)
    return text


# ---------------------------------------------------------------------------
# Block parsing
# ---------------------------------------------------------------------------

def is_table_separator(line: str) -> bool:
    s = line.strip()
    if "|" not in s:
        return False
    return bool(re.match(r"^\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?$", s))


def parse_table_row(line: str) -> list[str]:
    return [c.strip() for c in line.strip().strip("|").split("|")]


def make_callout(label: str, body_text: str, bg_color, border_color, styles) -> Table:
    label_para = Paragraph(f"<b>{label}</b>", styles["CalloutLabel"])
    body_para = Paragraph(inline_format(body_text), styles["CalloutBody"])

    label_cell = Table([[label_para]], colWidths=[0.95 * inch])
    label_cell.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), border_color),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))

    outer = Table(
        [[label_cell, body_para]],
        colWidths=[0.95 * inch, 5.55 * inch],
    )
    outer.setStyle(TableStyle([
        ("BACKGROUND", (1, 0), (1, 0), bg_color),
        ("LINEABOVE", (0, 0), (-1, 0), 0.5, border_color),
        ("LINEBELOW", (0, 0), (-1, 0), 0.5, border_color),
        ("LINEAFTER", (1, 0), (1, 0), 0.5, border_color),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (1, 0), (1, 0), 11),
        ("RIGHTPADDING", (1, 0), (1, 0), 11),
        ("TOPPADDING", (1, 0), (1, 0), 9),
        ("BOTTOMPADDING", (1, 0), (1, 0), 9),
    ]))
    return outer


def detect_callout(blockquote_text: str):
    t = blockquote_text.strip()
    for pat, label, bg, border in CALLOUT_RULES:
        m = re.search(pat, t)
        if m:
            body = (t[:m.start()] + t[m.end():]).strip()
            return label, body, bg, border
    return None


def render_paragraph(lines, styles) -> Paragraph:
    text = " ".join(line.strip() for line in lines)
    return Paragraph(inline_format(text), styles["Body"])


def render_list(items, styles, numbered=False):
    out = []
    for idx, item in enumerate(items, start=1):
        marker = f"{idx}." if numbered else "•"
        out.append(Paragraph(
            f"<b>{marker}</b>&nbsp;&nbsp;{inline_format(item)}",
            styles["ListItem"],
        ))
    return out


def render_table(header_cells, rows, styles, total_width=6.5 * inch):
    headers = [Paragraph(inline_format(c), styles["TableHeader"]) for c in header_cells]
    body = [
        [Paragraph(inline_format(c), styles["TableCell"]) for c in row]
        for row in rows
    ]
    data = [headers] + body
    n_cols = len(header_cells)
    col_width = total_width / n_cols
    t = Table(data, colWidths=[col_width] * n_cols, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PAL["teal"]),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("TOPPADDING", (0, 0), (-1, 0), 6),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, PAL["code_bg"]]),
        ("TOPPADDING", (0, 1), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.25, PAL["rule"]),
    ]))
    return t


def figure_flowable(name: str, gfx_paths: dict, styles, caption=None):
    img_path = gfx_paths.get(name)
    if not img_path or not img_path.exists():
        return [Paragraph(
            f"<i>[Figure {name} not found]</i>", styles["Caption"],
        )]
    img = Image(str(img_path), width=5.8 * inch, height=3.3 * inch, kind="proportional")
    img.hAlign = "CENTER"
    out = [Spacer(1, 6), img]
    if caption:
        out.append(Paragraph(caption, styles["Caption"]))
    else:
        out.append(Spacer(1, 10))
    return out


def md_to_flowables(text: str, styles: dict, gfx_paths: dict) -> list:
    flowables: list = []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].rstrip()
        stripped = line.lstrip()

        if not stripped:
            i += 1
            continue

        # Figure placeholder
        m = FIGURE_LINE.match(line)
        if m:
            flowables.extend(figure_flowable(m.group(1), gfx_paths, styles))
            i += 1
            continue

        # Horizontal rule
        if stripped in ("---", "***"):
            flowables.append(HRFlowable(
                width="100%", thickness=0.5, color=PAL["rule"],
                spaceBefore=8, spaceAfter=8,
            ))
            i += 1
            continue

        # Headers
        if stripped.startswith("# "):
            flowables.append(Paragraph(inline_format(stripped[2:]), styles["H1"]))
            i += 1
            continue
        if stripped.startswith("## "):
            flowables.append(Paragraph(inline_format(stripped[3:]), styles["H2"]))
            i += 1
            continue
        if stripped.startswith("### "):
            flowables.append(Paragraph(inline_format(stripped[4:]), styles["H3"]))
            i += 1
            continue

        # Table
        if "|" in stripped and i + 1 < len(lines) and is_table_separator(lines[i + 1]):
            header = parse_table_row(stripped)
            j = i + 2
            rows = []
            while j < len(lines) and "|" in lines[j].lstrip() and lines[j].strip():
                rows.append(parse_table_row(lines[j]))
                j += 1
            flowables.append(render_table(header, rows, styles))
            flowables.append(Spacer(1, 10))
            i = j
            continue

        # Blockquote (callout)
        if stripped.startswith(">"):
            quote_lines = []
            while i < len(lines) and lines[i].lstrip().startswith(">"):
                ql = lines[i].lstrip()[1:].lstrip()
                quote_lines.append(ql)
                i += 1
            quote_text = re.sub(r"\s+", " ", " ".join(quote_lines)).strip()
            callout = detect_callout(quote_text)
            if callout:
                label, body, bg, border = callout
                flowables.append(make_callout(
                    label, body, PAL[bg], PAL[border], styles,
                ))
            else:
                flowables.append(make_callout(
                    "NOTE", quote_text,
                    PAL["note_bg"], PAL["note_border"], styles,
                ))
            flowables.append(Spacer(1, 10))
            continue

        # Unordered list
        if re.match(r"^[-*]\s+", stripped):
            items = []
            while i < len(lines) and re.match(r"^[-*]\s+", lines[i].lstrip()):
                items.append(re.sub(r"^[-*]\s+", "", lines[i].lstrip()))
                i += 1
            flowables.extend(render_list(items, styles, numbered=False))
            flowables.append(Spacer(1, 6))
            continue

        # Ordered list
        if re.match(r"^\d+\.\s+", stripped):
            items = []
            while i < len(lines) and re.match(r"^\d+\.\s+", lines[i].lstrip()):
                items.append(re.sub(r"^\d+\.\s+", "", lines[i].lstrip()))
                i += 1
            flowables.extend(render_list(items, styles, numbered=True))
            flowables.append(Spacer(1, 6))
            continue

        # Paragraph
        para_lines = [line]
        i += 1
        while i < len(lines):
            nxt = lines[i].rstrip()
            if not nxt.strip():
                break
            if nxt.lstrip().startswith(("#", ">", "---", "***", "| ")):
                break
            if FIGURE_LINE.match(nxt):
                break
            if re.match(r"^[-*]\s+", nxt.lstrip()):
                break
            if re.match(r"^\d+\.\s+", nxt.lstrip()):
                break
            para_lines.append(nxt)
            i += 1
        flowables.append(render_paragraph(para_lines, styles))

    return flowables


# ---------------------------------------------------------------------------
# Title page + decorations
# ---------------------------------------------------------------------------

def make_title_page(styles) -> list:
    today = dt.date.today().isoformat()
    return [
        Spacer(1, 1.6 * inch),
        Paragraph("CHAPTER 5", styles["TitleEyebrow"]),
        Paragraph("Knowledge Graph<br/>Learning", styles["TitleMain"]),
        HRFlowable(
            width="35%", thickness=1.4, color=PAL["teal"],
            spaceBefore=10, spaceAfter=24, hAlign="CENTER",
        ),
        Paragraph(
            "A Plain-English Companion to<br/><i>AI-Powered Search</i>",
            styles["TitleSubtitle"],
        ),
        Spacer(1, 8),
        Paragraph(
            "based on the work of<br/>"
            "<b>Trey Grainger</b> &nbsp;·&nbsp; "
            "<b>Doug Turnbull</b> &nbsp;·&nbsp; "
            "<b>Max Irwin</b>",
            styles["TitleFootnote"],
        ),
        Spacer(1, 2.0 * inch),
        Paragraph(f"Generated {today}", styles["TitleFootnote"]),
        PageBreak(),
    ]


def make_toc(styles) -> list:
    flowables = [Paragraph("Contents", styles["H1"])]
    sections = [
        ("Section 1", "Knowledge Graphs: Connecting the Dots"),
        ("Section 2", "Your Search Engine Already Knows More Than You Think"),
        ("Section 3", "Teaching a Computer to Read Between the Lines"),
        ("Section 4", "Finding Hidden Connections in Your Words"),
        ("Section 5", "Putting It All Together: Smarter Search"),
        ("Reference",  "Glossary  ·  Cheat sheet"),
    ]
    rows = [[s, t] for s, t in sections]
    flowables.append(render_table(["", "Title"], rows, styles))
    flowables.append(Spacer(1, 16))
    return flowables


def _draw_header_footer(canvas_obj, doc, on_title=False):
    canvas_obj.saveState()
    page_w, page_h = letter

    if not on_title:
        # Top-right strip
        canvas_obj.setFont("Helvetica", 8)
        canvas_obj.setFillColor(PAL["muted"])
        canvas_obj.drawRightString(
            page_w - 0.85 * inch, page_h - 0.5 * inch,
            "Chapter 5  ·  Plain English Edition",
        )
        # Top-left accent
        canvas_obj.setFillColor(PAL["teal"])
        canvas_obj.rect(0.85 * inch, page_h - 0.55 * inch, 0.5 * inch, 2,
                        fill=1, stroke=0)
        # Bottom-center page number
        canvas_obj.setFont("Helvetica", 9)
        canvas_obj.setFillColor(PAL["muted"])
        canvas_obj.drawCentredString(page_w / 2.0, 0.5 * inch,
                                     f"— {canvas_obj.getPageNumber()} —")
    canvas_obj.restoreState()


def first_page_cb(canvas_obj, doc):
    _draw_header_footer(canvas_obj, doc, on_title=True)


def later_pages_cb(canvas_obj, doc):
    _draw_header_footer(canvas_obj, doc, on_title=False)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    here = Path(__file__).parent.resolve()
    content_dir = here / "content"
    graphics_dir = here / "graphics"

    # 1. Regenerate all graphics
    gfx_paths = gfx_module.build_all(graphics_dir)

    # 2. Build styles
    styles = build_styles()

    # 3. Read content files in filename order
    md_files = sorted(content_dir.glob("*.md"))
    if not md_files:
        raise SystemExit(f"No content files found in {content_dir}")

    out_path = here / "chapter-5-plain-english.pdf"
    doc = SimpleDocTemplate(
        str(out_path),
        pagesize=letter,
        leftMargin=0.95 * inch, rightMargin=0.95 * inch,
        topMargin=0.9 * inch, bottomMargin=0.9 * inch,
        title="Chapter 5: Knowledge Graph Learning — Plain English Edition",
        author="A friendly retelling of Chapter 5 of AI-Powered Search by Trey Grainger, Doug Turnbull, and Max Irwin",
        subject="A friendly retelling of Chapter 5 of AI-Powered Search.",
    )

    story = []
    story.extend(make_title_page(styles))

    # Render each markdown file; sections (01-05) start on a new page
    for md_path in md_files:
        body = md_path.read_text()
        flowables = md_to_flowables(body, styles, gfx_paths)
        story.extend(flowables)
        story.append(PageBreak())

        # Insert TOC after the front matter (file 00_*)
        if md_path.name.startswith("00_"):
            story.extend(make_toc(styles))
            story.append(PageBreak())

    # Build
    doc.build(
        story,
        onFirstPage=first_page_cb,
        onLaterPages=later_pages_cb,
    )
    print(f"Wrote {out_path}  ({out_path.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
